model: "convnet"

globaux:
  BATCH_SIZE: 512
  PATIENCE: 10
  VERBOSE: "WARNING"   # set to DEBUG to see step-by-step training logs
  COMPILE: True

scratch_training:
  run_execution: True
  loss_name: "PWGLossRegularized"
  learning_rate: 1.0e-3
  l2_weight_decay: 1.0e-2
  num_epoch: 100
  loss_alpha: 1.0
  augmentation: True
  method_FT: "scratch_training"
  loader_factory: "get_challenge_train_loader"
  val_loader_factory: "get_challenge_val_loader"
  val_split: "val_samp"
  method_kwargs: {}
  
domain_adaptation_training:
  run_execution: False

probing_training:
  run_execution: False

lora_training:
  run_execution: False

