# Model
model_name: "facebook/dinov3-vitb16-pretrain-lvd1689m"
type: dino_cnn
embedding_dir: "embedding-vitb16+patches"
embed_dim: 768
save_fp16: true
embed_batch_size: 32
save_patches: true

# Data
n_bins: 20
train_use_noisy: true
val_use_noisy: true
