# Model
model_name: "facebook/dinov3-vitb16-pretrain-lvd1689m"
type: dino_cnn
embedding_dir: "embedding-vitb16+patches"
embed_dim: 768
save_fp16: true
embed_batch_size: 32
save_patches: true

# Data
n_bins: 20
train_use_noisy: true
val_use_noisy: true

# CNN
patch_use_cls: true
smooth_alpha: 0       
lp_lr: 1.0e-3
lp_weight_decay: 1.0e-4
lp_epochs: 100
lp_batch_size: 2048
lp_loss: "CompoundLoss"
lp_loss_alpha: 1.0    
lp_loss_beta: 0.1    
lp_loss_gamma: 1.0    
lp_loss_kappa: 0.0    
lp_patience: 5
lp_dropout: 0.2


# optuna_n_trials: 50
# optuna_epochs: 20   # short runs during search
# optuna_patience: 5   # short runs during search
