model: 'tf_efficientnetv2_s.in21k'

globaux:
  NUM_CLASSES: 1
  PATIENCE: 60
  BATCH_SIZE: 128
  VERBOSE: "WARNING"

cnn_ft_training:
  run_execution: True
  loss_name: "PWGLossRegularized"
  learning_rate: 1.0e-3
  l2_weight_decay: 1.0e-2
  num_epoch_head: 200
  num_epoch_per_phase: 0
  n_phases: 0
  lr_decay_factor: 0.1
  augmentation: True
  method_FT: "cnn_ft"
  method_kwargs:
    probing_type: "mlp_probing"
    hidden_size: 512

scratch_training:
  run_execution: False
domain_adaptation_training:
  run_execution: False
probing_training:
  run_execution: False
lora_training:
  run_execution: False