domain_adaptation_training:
  augmentation: true
  learning_rate: 5.0e-05
  loader_factory: get_celeba_train_loader
  loss_name: BCE
  method_FT: domain_adaptation
  method_kwargs:
    alpha: 16
    dropout: 0.2
    rank: 8
  num_epoch: 1
  run_execution: true
  val_loader_challenge: get_challenge_val_loader
  val_loader_factory: get_celeba_val_loader
  val_split: val_samp
globaux:
  BATCH_SIZE: 32
  EPOCHS: 1
  NUM_CLASSES: 1
  N_BINS: 20
  N_SAMPLE: 5000
  PATIENCE: 5
  SEED: 42
lora_training:
  augmentation: true
  learning_rate: 0.0002
  loader_factory: get_challenge_train_loader
  loss_name: nMSE
  method_FT: lora_training
  method_kwargs:
    alpha: 16
    dropout: 0.2
    rank: 8
  num_epoch: 1
  run_execution: true
  val_loader_factory: get_challenge_val_loader
  val_split: val_samp
model: vit_tiny_patch16_224
probing_training:
  augmentation: true
  learning_rate: 0.001
  loader_factory: get_challenge_train_loader
  loss_name: nMSE
  method_FT: probing_training
  method_kwargs:
    alpha: 16
    dropout: 0.2
    hidden_size: 512
    probing_type: mlp_probing
    rank: 8
  num_epoch: 1
  run_execution: true
  val_loader_factory: get_challenge_val_loader
  val_split: val_samp
