globaux:
  SEED : 42
  N_SAMPLE : 5000
  N_BINS : 20
  NUM_CLASSES : 1
  PATIENCE : 5
  BATCH_SIZE : 32
  VERBOSE: "WARNING"   # set to DEBUG to see step-by-step training logs
  
domain_adaptation_training:
  run_execution: False
  loss_name: "BCE"
  learning_rate: 5.0e-5
  num_epoch: 1
  augmentation: True
  method_FT: "domain_adaptation"
  loader_factory: "get_celeba_train_loader"
  val_loader_factory: "get_celeba_val_loader"
  val_loader_challenge: "get_challenge_val_loader"
  val_split: "val_samp"
  method_kwargs:
    rank: 8
    alpha: 16
    dropout: 0.2

probing_training:
  run_execution: True
  loss_name: "nMSE"
  learning_rate: 1.0e-3
  num_epoch: 1
  augmentation: True
  method_FT: "probing_training"
  loader_factory: "get_challenge_train_loader"
  val_loader_factory: "get_challenge_val_loader"
  val_split: "val_samp"
  method_kwargs:
    rank: 8
    alpha: 16
    dropout: 0.2
    probing_type: "mlp_probing"
    hidden_size: 512

lora_training:
  run_execution: True
  loss_name: "nMSE"
  learning_rate: 2.0e-4
  num_epoch: 1
  augmentation: True
  "method_FT": "lora_training"
  loader_factory: "get_challenge_train_loader"
  val_loader_factory: "get_challenge_val_loader"
  val_split: "val_samp"
  method_kwargs:
    rank: 8
    alpha: 16
    dropout: 0.2



