globaux:
  SEED                : 43
  N_SAMPLE            : 100000
  N_BINS              : 20
  NUM_CLASSES         : 1
  PATIENCE            : 5
  BATCH_SIZE          : 256
  EPS                 : 1e-8

loader:
  val_split           : "val_samp"
  train_loader_factory: "get_challenge_train_loader"
  val_loader_factory  : "get_challenge_val_loader"

augmentation:
  status              : True
  warm_start          : 0
  warm_stop           : 18
  augmentation_factor : 2





